version: '3'
services:
  app:
    container_name: fantasy-11
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo-db-fantasy-11
    image: mongo
    ports:
      - '27017:27017'
